const money=n=>new Intl.NumberFormat('hu-HU',{maximumFractionDigits:0}).format(n)+' Ft';
const num=(n,d=2)=>new Intl.NumberFormat('hu-HU',{maximumFractionDigits:d}).format(n);
const calculators=[
{id:'percent',title:'Százalékkalkulátor',category:'Mindennapi',icon:'%',desc:'Mennyi egy szám adott százaléka?',fields:[['base','Alapérték','number'],['percent','Százalék (%)','number']],calc:v=>({main:num(v.base*v.percent/100),sub:`${num(v.percent)}% ennyi a(z) ${num(v.base)} értékből.`})},
{id:'vat',title:'ÁFA-kalkulátor',category:'Pénzügy',icon:'🧾',desc:'Nettó, ÁFA és bruttó összeg számítása.',fields:[['net','Nettó összeg (Ft)','number'],['rate','ÁFA kulcs (%)','number','27']],calc:v=>{const vat=v.net*v.rate/100;return{main:money(v.net+vat),sub:`ÁFA: ${money(vat)} · Nettó: ${money(v.net)}`}}},
{id:'bmi',title:'BMI-kalkulátor',category:'Egészség',icon:'⚖️',desc:'Testtömegindex gyors kiszámítása.',fields:[['weight','Testsúly (kg)','number'],['height','Magasság (cm)','number']],calc:v=>{const b=v.weight/((v.height/100)**2);const c=b<18.5?'sovány':b<25?'normál tartomány':b<30?'túlsúlyos tartomány':'elhízás tartománya';return{main:num(b,1),sub:`Besorolás: ${c}.`}}},
{id:'fuel',title:'Üzemanyagköltség',category:'Autó',icon:'⛽',desc:'Út költsége fogyasztás alapján.',fields:[['distance','Távolság (km)','number'],['consumption','Fogyasztás (l/100 km)','number'],['price','Üzemanyagár (Ft/l)','number']],calc:v=>{const liters=v.distance*v.consumption/100;return{main:money(liters*v.price),sub:`Szükséges üzemanyag: ${num(liters)} liter.`}}},
{id:'compound',title:'Kamatos kamat',category:'Pénzügy',icon:'📈',desc:'Befektetés jövőértékének becslése.',fields:[['capital','Kezdőtőke (Ft)','number'],['monthly','Havi befizetés (Ft)','number','0'],['rate','Éves hozam (%)','number'],['years','Időtáv (év)','number']],calc:v=>{const r=v.rate/100/12,n=v.years*12;const fv=v.capital*((1+r)**n)+(r?v.monthly*(((1+r)**n-1)/r):v.monthly*n);return{main:money(fv),sub:`Befizetett összeg: ${money(v.capital+v.monthly*n)}.`}}},
{id:'loan',title:'Hiteltörlesztő',category:'Pénzügy',icon:'🏦',desc:'Várható havi annuitásos törlesztőrészlet.',fields:[['amount','Hitelösszeg (Ft)','number'],['rate','Éves kamat (%)','number'],['years','Futamidő (év)','number']],calc:v=>{const r=v.rate/100/12,n=v.years*12;const p=r?v.amount*r*(1+r)**n/((1+r)**n-1):v.amount/n;return{main:money(p)+' / hó',sub:`Teljes visszafizetés kb. ${money(p*n)}.`}}},
{id:'discount',title:'Kedvezménykalkulátor',category:'Mindennapi',icon:'🏷️',desc:'Akciós ár és megtakarítás számítása.',fields:[['price','Eredeti ár (Ft)','number'],['discount','Kedvezmény (%)','number']],calc:v=>{const save=v.price*v.discount/100;return{main:money(v.price-save),sub:`Megtakarítás: ${money(save)}.`}}},
{id:'pace',title:'Tempó-kalkulátor',category:'Egészség',icon:'🏃',desc:'Futótempó kiszámítása táv és idő alapján.',fields:[['distance','Távolság (km)','number'],['minutes','Idő (perc)','number']],calc:v=>{const p=v.minutes/v.distance,m=Math.floor(p),s=Math.round((p-m)*60);return{main:`${m}:${String(s).padStart(2,'0')} perc/km`,sub:`Átlagsebesség: ${num(60/p,1)} km/h.`}}},
{id:'area',title:'Területátváltó',category:'Átváltó',icon:'📐',desc:'Négyzetméter és gyakori területegységek.',fields:[['sqm','Terület (m²)','number']],calc:v=>({main:`${num(v.sqm/10000,4)} hektár`,sub:`${num(v.sqm*10.7639)} négyzetláb · ${num(v.sqm/100)} ár`})}
];
const $=s=>document.querySelector(s),grid=$('#calculatorGrid'),dialog=$('#calcDialog');
let favorites=JSON.parse(localStorage.getItem('kb-favorites')||'[]');let recent=JSON.parse(localStorage.getItem('kb-recent')||'[]');
function card(c){const el=document.createElement('article');el.className='card';el.innerHTML=`<button class="fav ${favorites.includes(c.id)?'active':''}" aria-label="Kedvenc">★</button><div class="card-icon">${c.icon}</div><h3>${c.title}</h3><p>${c.desc}</p>`;el.addEventListener('click',e=>{if(e.target.classList.contains('fav')){toggleFav(c.id);return}openCalc(c)});return el}
function render(){const q=$('#searchInput').value.trim().toLocaleLowerCase('hu');const list=calculators.filter(c=>(c.title+' '+c.category+' '+c.desc).toLocaleLowerCase('hu').includes(q));grid.replaceChildren(...list.map(card));$('#resultCount').textContent=`${list.length} eszköz`;$('#emptyState').hidden=!!list.length;renderStored()}
function renderStored(){const fav=calculators.filter(c=>favorites.includes(c.id));$('#favoritesSection').hidden=!fav.length;$('#favoritesGrid').replaceChildren(...fav.map(card));const rec=recent.map(id=>calculators.find(c=>c.id===id)).filter(Boolean);$('#recentSection').hidden=!rec.length;$('#recentGrid').replaceChildren(...rec.map(card))}
function toggleFav(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('kb-favorites',JSON.stringify(favorites));render()}
function openCalc(c){recent=[c.id,...recent.filter(x=>x!==c.id)].slice(0,4);localStorage.setItem('kb-recent',JSON.stringify(recent));$('#dialogCategory').textContent=c.category;$('#dialogTitle').textContent=c.title;$('#dialogBody').innerHTML=`<form class="form-grid">${c.fields.map(f=>`<div class="field"><label for="${f[0]}">${f[1]}</label><input id="${f[0]}" name="${f[0]}" type="${f[2]}" value="${f[3]||''}" inputmode="decimal" step="any" required></div>`).join('')}<button class="primary" type="submit">Kiszámolom</button></form><div id="calcResult"></div><p class="formula-note">A számítás a megadott adatokból, a böngésződben történik. Az eredmény tájékoztató jellegű.</p>`;$('#dialogBody form').onsubmit=e=>{e.preventDefault();const v={};new FormData(e.target).forEach((x,k)=>v[k]=Number(String(x).replace(',','.')));const r=c.calc(v);$('#calcResult').innerHTML=`<div class="result"><small>Eredmény</small><strong>${r.main}</strong><small>${r.sub}</small></div>`};dialog.showModal();renderStored()}
$('#closeDialog').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});$('#searchInput').addEventListener('input',render);$('#clearRecent').onclick=()=>{recent=[];localStorage.removeItem('kb-recent');renderStored()};
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
render();
